name: lezato
description: An restaurant app for hungry belly.

publish_to: 'none'

version: 3.0.2+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^2.5.0
  lottie: ^1.0.1
  http: ^0.13.3
  provider: ^5.0.0
  intl: ^0.17.0
  android_alarm_manager: ^2.0.0
  flutter_local_notifications: ^5.0.0
  rxdart: any

  #Hive Database
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  mockito: ^5.0.10

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/

  fonts:
    - family: Pattaya
      fonts:
        - asset: fonts/Pattaya-Regular.ttf